[theme]
theme = "solarized-dark"

[icons]
# name = "awesome"
icons = "material"

[[block]]
block = "focused_window"


[[block]]
block = "net"
device = "wlp2s0"
format = " $icon $ssid $ip "
interval = 30
missing_format = ""

[[block]]
block = "net"
device = "enp0s31f6"
format = " $icon $ip "
interval = 30
missing_format = ""

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $used/$total "
interval = 120
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization $frequency "

[[block]]
block = "temperature"
interval = 20
format = " $icon $min~$max "
#chip = "*"

# [[block]]
# block = "battery"
# interval = 10
# format = " $icon $percentage {$time |} "
# missing_format = ""
# if_command = "ls /sys/class/power_supply/BAT*"

# [[block]]
# block = "backlight"
# format = " $icon $brightness "
# if_command = "ls /sys/class/backlight/*"
# #missing_format = ""  # FIXME: This is missing

[[block]]
block = "hueshift"
format = " 😎 $temperature "
# hue_shifter = "gammastep"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %l:%M%p')"


# [[block]]
# block = "net"
# device = "wlp2s0"
# ssid = true
# #ip = true
# interval = 30
# #bitrate = true
# speed_up = false
# speed_down = false

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 120
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"
# #format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
# #format_swap = "{SUm}MB/{STm}MB({SUp}%)"
# interval = 5
# clickable = true
# warning_mem = 80
# warning_swap = 80
# critical_mem = 95
# critical_swap = 95

# [[block]]
# block = "cpu"
# interval = 2
# frequency = true

# #[[block]]
# #block = "load"
# #interval = 5
# #format = "{1m}"

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 20
# format = "{min}~{max}°"
# chip = "coretemp-*"

# #[[block]]
# #block = "battery"
# #interval = 10
# #show = "both"

# #[[block]]
# #block = "backlight"

# [[block]]
# block = "toggle"
# command_state = "systemctl --user -q is-active redshift && echo on"
# command_on = "systemctl --user start redshift"
# command_off = "systemctl --user stop redshift"
# #icon_on = "backlight_empty"
# #icon_off = "backlight_full"
# text = "R"
# interval = 60

# [[block]]
# block = "sound"

# [[block]]
# block = "time"
# interval = 10
# format = "%a %Y-%m-%d %l:%M%p"
